feat(civo-github): add gpu operator to allow use of GPU nodes
konstructio/gitops-template pull request #789
Opened 2024-08-15 13:23 UTC by mrsimonemms

## Description

This is a piece of work that requires a bit of thought. For Civo-GitHub, I've added the ability to use GPU nodes. This requires some changes to how things work which could cause problems.

### Uncontroversial changes

- Install the NVIDIA GPU operator. This is based upon the work done in https://github.com/civo-learn/civo-gpu-operator-tf, but tailored it to our needs. I don't particularly like the `is_gpu` flag as it assumes that all GPU nodes start `g4g.` or `an.` which may not always be true - if anyone has a better idea how to achieve this, I'm all ears (I had hoped that `data.civo_size` would have it, but it doesn't).

### Controversial changes

- I've had to bump Crossplane to v1.16.0 (from v1.12.2). This is because I need to use the `helm_release` Terraform resource, which has a problem with the Crossplane provider not being able to download the charts (see https://github.com/crossplane-contrib/provider-terraform/issues/54). In order to fix this, I need to use an `emptyDir` volume mount on the Crossplane provider's pod and the v1.12.2 version of the CRD doesn't have it in `ControllerConfig.pkg.crossplane.io/v1alpha1`
- This means that `civo-github` has a different Crossplane version to all the other providers which I feel should probably be consistent.
- We probably should also switch from using `ControllerConfig` as it's [deprecated as of v1.11 and will be removed at some future date](https://docs.crossplane.io/latest/concepts/providers/#controller-configuration). Again, this is a big change to do across all providers.

## Related Issue(s)

Fixes #

## How to test

>* *IMPORTANT** the cheapest GPU node costs $1,200 per month ($1+ an hour) - don't leave it running.

1. Deploy Civo GitHub

```shell
/path/to/kubefirst civo create \
--alerts-email <EMAIL> \
--github-org <ORG> \
--cluster-name <NAME> \
--domain-name <DOMAIN> \
--gitops-template-branch sje/crossplane-version \
--cloud-region LON1
```

2. In the console, deploy a single node GPU cluster - suggest using a `g4g.40.kube.small` 
![image](https://github.com/user-attachments/assets/67aba56c-98ce-4002-8083-cacab0c8816d)

2024-08-20 15:55 UTC, patrickdappollonio requested changes

2024-08-20 15:55 UTC, patrickdappollonio commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +      "pod-security.kubernetes.io/enforce" = "privileged"
Any reason why the limitation?

2024-08-20 15:55 UTC, patrickdappollonio commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +            sleep infinity
I would recommend changing this (and maybe the container) to a kubernetes/pause container that can correctly assert or trap signals.

`sleep infinity` inside a bash command will only trap a signal after it has been issued if the sleep command is done (which in this case it never is). That's why kubernetes relies better on kubernetes/pause than any sleep mechanism since they are a bit wasteful for this purpose.

More info: https://mywiki.wooledge.org/SignalTrap#When_is_the_signal_handled.3F

2024-08-20 15:55 UTC, patrickdappollonio commented on civo-github/terraform/civo/modules/workload-cluster/main.tf
> +  cluster_type     = local.is_gpu ? "talos" : "k3s" # k3s doesn't support GPU
Is this our implementation of k3s? Because k3s does support it (you have to jump over a few hoops but I've done it in the past)

https://docs.k3s.io/advanced#nvidia-container-runtime-support

2024-08-21 08:26 UTC, mrsimonemms commented on civo-github/terraform/civo/modules/workload-cluster/main.tf
> +  cluster_type     = local.is_gpu ? "talos" : "k3s" # k3s doesn't support GPU
Must be a Civo thing then - if you don't set to `talos`, it errors when using a GPU node

2024-08-21 08:29 UTC, mrsimonemms commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +            sleep infinity
This is straight out of the [Civo guide](https://github.com/civo-learn/civo-gpu-operator-tf/blob/main/infra/tf/fake-operator-ready.tf#L43,L52). I don't particularly like this, but the fake-operator pod is required to prompt the operator to apply the labels/annotations to the node.

I'll have a look at your suggestion, but this might need to be stay as-is if can't get it to work.

2024-08-21 08:31 UTC, mrsimonemms commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +      "pod-security.kubernetes.io/enforce" = "privileged"
It's required in the NVIDIA docs if [you're using pod security admissions](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html#prerequisites). As this is a PoC, I think it should be in to avoid any issues where it's not applied.

2024-08-21 12:53 UTC, patrickdappollonio commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +      "pod-security.kubernetes.io/enforce" = "privileged"
I don't think I read it as "it's required". The statement starts with "If your cluster uses Pod Security Admission (PSA) to restrict the behavior of pods" but I'm not sure if you installed it that it makes this a requirement.

2024-08-21 12:55 UTC, patrickdappollonio commented on civo-github/terraform/civo/modules/workload-cluster/gpu.tf
> +            sleep infinity
I see. I know it's required (several other things come out of similar things like enable higher file descriptor limits so this pattern is quite common).

While that might be in thekr guide, I would want to avoid ourselves having to troubleshoot struggling-to-finalize pods if we can leverage pause instead. Happy to help you make the conversion if need be!

2024-08-21 15:19 UTC, fharper commented on civo-github/terraform/civo/modules/workload-cluster/main.tf
> +  cluster_type     = local.is_gpu ? "talos" : "k3s" # k3s doesn't support GPU
I think we should document that. As a rule of thumb, any different behavior from one cloud to the other, or limitations we have (either from us or the cloud provider) or things that we implemented in one cloud/Git provider/UI&CLI that isn't the same everywhere, should be documented :)

Prior to that though, I would check with Civo to see if it's a known limitation on their side, or a bug, or something on our side. Did we check with them yet?

2024-08-21 18:50 UTC, fharper commented on civo-github/terraform/civo/modules/workload-cluster/main.tf
> +  cluster_type     = local.is_gpu ? "talos" : "k3s" # k3s doesn't support GPU
So we had a discussion on Slack instead of here about documenting this, and here is the tl;dr:
- The limitation is from Civo, and know: it's not a bug.
- We will update the comment to reflect that it's not a limitation from K3s, nor kubefirst, but a Civo one, so it's clear to anyone looking at the code.
- We won't document that in the docs.

2024-11-28 15:30 UTC, closed without merging